spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foryourskintype
    #jdbc:h2:tcp://localhost/~/foryourskintype
    username: yanglet
    password: yanglet
    driver-class-name: com.mysql.cj.jdbc.Driver
    #org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace