spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/foryourskintype
#    jdbc:mysql://localhost:3306/foryourskintype
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace